### ISSUE TITLE
Shared data structures

### ISSUE THREAD

**Issue by asajeffrey** [elast0ny/mem_file#28]
Hi there! I've been playing with your crate as a way of improving the perf and API of Servo's inter-process communication, and came up with https://github.com/asajeffrey/shared-data

At the moment this is just basic shared data structures, e.g. boxes, vectors, and ref-counted pointers, but it's a start!

At the moment, there seems to be a pretty clean line between what `shared_memory` provides (access to shared memory as `*mut u8`) and what `shared-data` does (higher level safe APIs). Perhaps there are ideas that should be moved from one to the other? The only thing that's a bit funny right now is that `SharedMemCast` is in `shared_memory` and `SharedMemRef` (types you can take a reference to in shared memory) is in `shared-data`.

**Comment by elast0ny** [comment]
Hi, I took a look around your crate and it seems like a good idea but I think the separation between this basic shared_memory crate and yours is how it should be...

I can easily think of scenarios where authors might not want data structures or might want to have very close control on how the structures are implemented for high performance & safety. The Rust toolchain makes it very easy for user to import whatever building block they need.

Just out of curiosity, do you plan on making your data structure safe for concurrent accesses ? 
(eg : process1 pushes an element in a vector which doesnt fit in the current allocation so the data backing the vector moves into a different area. How will process2 using the same vector become aware of the changes ?)

**Comment by asajeffrey** [comment]
OK, sounds like we'll stick with the current split then.

The data structures should be thread safe, if they're not that's a bug! Shared arrays currently don't support growing, that would be a tricky API to implement. The API I'm working on at the moment is a shared version of channels, which does support growing but isn't random access so is a lot easier to implement.

Thanks!
