### ISSUE TITLE
Allow dynamic creation of locks/events

### ISSUE THREAD

**Issue by asajeffrey** [elast0ny/mem_file#29]
At the moment, the number and kinds of locks and events is fixed when creating the shared memory. There are APIs (like channels) where it would be useful to be able to create these dynamically, allocating them into the regular shared memory rather than the metadata. Is this doable?

**Comment by asajeffrey** [comment]
Related to #12.

**Comment by elast0ny** [comment]
This sounds like could be a useful feature,

I'm not exactly sure how the api would look but it could be something along the lines of : 
```Rust
//Rough api that someone could call to initialize a mutex at a given address
pub unsafe fn LockType::Mutex::init(shmem_ptr: *mut c_void) -> &'static dyn LockImpl
```


I'm happy to receive a PR or I will eventually take a look at implementing this when I get some free time !

**Comment by asajeffrey** [comment]
We could be explicit that this is being created in shared memory, with something like `SharedMemory::new_lock(&self, offset: usize, lock_type: LockType)`? We'd also probably want a way to find the size of a lock, perhaps by providing a type `SharedLock<LockType>`?

**Comment by elast0ny** [comment]
This is now possible through the [raw_sync ](https://github.com/elast0ny/raw_sync-rs) crate.
