### ISSUE TITLE
Is the implementation of `Deref` and `DerefMut` for locks safe?

### ISSUE THREAD

**Issue by asajeffrey** [elast0ny/mem_file#34]
The `ReadLockGuard` and `WriteLockGuard` types implement `Deref` and `DerefMut` respectively, but it is not obvious this is safe. For example, by locking the same area of memory at different types, I can get a `&usize` and an `&AtomicUsize` which alias, then storing into the `&AtomicUsize`  causes the `&usize` to become UB.

**Comment by asajeffrey** [comment]
This is from https://github.com/elast0ny/shared_memory-rs/issues/33#issuecomment-537482273 but is separate enough that I thought it was worth opening.

**Comment by elast0ny** [comment]
Follow up on : https://github.com/elast0ny/shared_memory-rs/issues/33#issuecomment-537513888
