### ISSUE TITLE
Using AtomicPtr like AtomicBool in raw example?

### ISSUE THREAD

**Issue by serzhiio** [elast0ny/mem_file#36]
Is it possible?

**Comment by asajeffrey** [comment]
The problem with `AtomicPtr` is that it uses the process address space, and different processes have different address spaces. You can't send pointers between processes.

**Comment by elast0ny** [comment]
It would be _possible_ but @asajeffrey highlighted why it would not be useful/valid to do so. Even the shared memory itself doesnt get mapped at the same address in two different processes that use it.

If you need pointer sized values to live in the shmem, you could use `Atomic[U/I]size`
