### ISSUE TITLE
`WriteLockable::wlock` accepts a mutable reference

### ISSUE THREAD

**Issue by mexus** [elast0ny/mem_file#37]
Hello @elast0ny  and thanks for such a useful library!

At the title stands, currently the `WriteLockable::wlock` methods takes `self` by a mutable (unique) reference, which I believe doesn't make a lot of sense: since the unique-mutalbe-borrow-check is performed in the runtime, the mutability requirement could be lifted.

While this inconvenience could be easily circumvented by opening the same shared memory area twice, it is still a circumvention and adds a seemingly unnecessary boilerplate.

My usecase for that is to access distinct indices simultaneously.

Do you think we could have it solved?

Thanks!

**Comment by mitsuhiko** [comment]
This is indeed quite weird. I ran into this myself earlier today.
