### ISSUE TITLE
SharedMemory::create causes "Bus error (core dumped)"

### ISSUE THREAD

**Issue by cswinter** [elast0ny/mem_file#41]
I've been trying out shared_memory and it seems to working as expect on Mac, but when running inside a docker container based off `rust:1.38` my program invariable crashes with the error message "Bus error (core dumped)" when calling `SharedMem::create(LockType::RwLock, 1024)`.

**Comment by elast0ny** [comment]
Hi, i have released a simplified version of the crate which should eliminate most unsoundness bugs. I will close the issue but feel free to re-open if this is still present in version 0.11.0
