### ISSUE TITLE
Where are the examples mentioned in the documentation?

### ISSUE THREAD

**Issue by evandrocoan** [elast0ny/mem_file#43]
https://docs.rs/shared_memory/0.10.0/shared_memory/

You could put a relative link?

![image](https://user-images.githubusercontent.com/5332158/80422752-1cb05e00-88b5-11ea-8777-9fcad033e16f.png)

**Comment by elast0ny** [comment]
Hi, usually for Rust project, standalone examples are stored in the `examples/` folder at the root of the crate. (So they can be picked up by cargo e.g `cargo run --example basic` will run `examples/basic.rs`)

https://github.com/elast0ny/shared_memory-rs/tree/master/examples

I'll make that a link in the next version i release
