### ISSUE TITLE
`set_owner` method has no effect on Linux

### ISSUE THREAD

**Issue by vitvakatu** [elast0ny/mem_file#48]
Hello

As far as I can see, `Shmem::set_owner` method does not affect the behavior of `unix::MapData`, as `MapData::owner` depends only on called function (whether it is `create_mapping` or `open_mapping`).

**Comment by elast0ny** [comment]
Hi, thank you for reporting this issue. You're right that as part of `Shmem::set_owner`, the `unix::MapData::owner` field should be updated.

I will fix it as soon as I have some spare time,

Thanks !
