### ISSUE TITLE
Shmem::as_slice will be unsound.

### ISSUE THREAD

**Issue by 197g** [elast0ny/mem_file#49]
https://github.com/elast0ny/shared_memory-rs/blob/b616fc40956dd7451dab88a7bb54e09d50bfee6e/src/lib.rs#L231-L238

As far as I can tell these are unpublished but those methods are not sound. The first return type, `&[u8]`, requires that the range of bytes is immutable while the second, `&mut [u8]`, requires that it is unique. Furthermore both require them to actually be initialized. Neither can be guaranteed for shared memory.

These methods would need to be `unsafe` but the requirements are almost impossible to validate. A somewhat better return type would be `&UnsafeCell<[MaybeUninit<u8>]>` which guarantees almost nothing about the contents except that the memory exists.

**Comment by elast0ny** [comment]
Hi @HeroicKatora , thank you for spotting this issue.

I will mark both methods as unsafe. At least keeping them will provide a shorter form to get slices out of the mapping despite it still being unsafe.

**Comment by 197g** [comment]
That seems reasonable as well.
