### ISSUE TITLE
New crates.io release required

### ISSUE THREAD

**Issue by phil-opp** [elast0ny/mem_file#69]
The latest crates.io version `0.11.4` does no longer work because it still has a `0.*` wildcard dependency on `nix`. Thus, cargo uses the latest available version, `nix` 0.22, which is not compatible with this crate without adjustments (see #68). The wildcard dependencies were fixed in January as part of https://github.com/elast0ny/shared_memory-rs/pull/57, but this wasn't released to crates.io yet.

**Comment by p-avital** [comment]
I’ve made PR #68 to fix wildcard while bumping supported nix version to 0.22 in the beginning of this week. I guess @elast0ny is currently otherwise occupied.

**Comment by rdfriese** [comment]
I can verify we are having the same issue

**Comment by elast0ny** [comment]
Thanks for the issue & PR, I will take a look in the next few days and will publish 0.12 👍

**Comment by elast0ny** [comment]
I updated master to use latest `nix` but also remembered why I never published version 12, i wrote [an issue](https://github.com/elast0ny/shared_memory-rs/issues/71) to track what I will do about it.
