### ISSUE TITLE
I cannot use systemd_journal_logger with shared memory

### ISSUE THREAD

**Issue by vandercijr** [elast0ny/mem_file#85]
I am not able to use shared_memory lib and systemd_journal_logger  lib together when I run binary file without debug symbols

For example 

```
`use log::LevelFilter;

fn main() {
  systemd_journal_logger::init().unwrap();

  log::set_max_level( LevelFilter::Debug);

  log::warn!("A warning.");
  log::error!("An error");
}    `
```

And this dependencies
```

`[dependencies]
serde =  { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "=0.4.14"
systemd-journal-logger = "=0.3.1"

```
everything works perfectly when running ./target/release/xyz

but if I include shared_memory It stops working

I checked in sm source code that implements a log crate, why dont use standard log api implementation ?|
thanks

**Comment by jcaesar** [comment]
Well, there's your problem: https://github.com/elast0ny/shared_memory/pull/81

**Comment by elast0ny** [comment]
Hi, 

(thx @jcaesar ! )

Seems like you're most likely running into a bug from a previous versions (it is hard to tell as you didn't include the shared memory dependency info). Try using the lastest version. If it still fails, we can reopen the issue !

**Comment by jcaesar** [comment]
> most likely running into a bug from a previous version

@elast0ny Hm? [crates.io](https://crates.io/crates/shared_memory) still has 0.12.2, and that [does have](https://docs.rs/crate/shared_memory/0.12.2/source/Cargo.toml) that problem. Am I missing something?

**Comment by elast0ny** [comment]
I just pushed 0.12.3, sorry for the delay
