### ISSUE TITLE
The latest version 0.12.2 on crates.io is still wrong

### ISSUE THREAD

**Issue by nickkuk** [elast0ny/mem_file#87]
There is something wrong with the latest version of this crate [https://crates.io/crates/shared_memory/0.12.2](https://crates.io/crates/shared_memory/0.12.2): it requires log crate, have
```toml
default = ["log/release_max_level_off"]
```
and does not match with version in this repository.

**Comment by elast0ny** [comment]
Thanks for nudging me on this.

Should be fixed in 0.12.3
